<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>EraWheel</AssemblyName>
    <OutputType>Library</OutputType>
    <LangVersion>9.0</LangVersion>
    <Version>1.0.3</Version>
    <AssemblyVersion>1.0.3.0</AssemblyVersion>
    <FileVersion>1.0.3.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>lib/Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>lib/UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>lib/UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>lib/UnityEngine.UI.dll</HintPath>
      <Private>false</Private>
     </Reference>
    <Reference Include="UnityEngine.JSONSerializeModule" Condition="Exists('lib/UnityEngine.JSONSerializeModule.dll')">
      <HintPath>lib/UnityEngine.JSONSerializeModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule" Condition="Exists('lib/UnityEngine.IMGUIModule.dll')">
      <HintPath>lib/UnityEngine.IMGUIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule" Condition="Exists('lib/UnityEngine.InputLegacyModule.dll')">
      <HintPath>lib/UnityEngine.InputLegacyModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="NeoModLoader">
      <HintPath>lib/NeoModLoader.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="System.Net.Http" />
  </ItemGroup>

  <ItemGroup>
    <None Update="mod.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Config/**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources/**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Localization/**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
