<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="../../../EraWheel/src/**/*.cs" />
  </ItemGroup>

  <ItemGroup>
    <WorldBoxManaged Include="../../../tools/WorldBox.Managed/*.dll" />
    <Reference Include="@(WorldBoxManaged)">
      <HintPath>%(Identity)</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
